//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoonAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LagoonEntities : DbContext
    {
        public LagoonEntities()
            : base("name=LagoonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_TMPCLP386101> C_TMPCLP386101 { get; set; }
        public virtual DbSet<Order_Detail> Order_Detail { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Feedback> Product_Feedback { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Store_Feedback> Store_Feedback { get; set; }
        public virtual DbSet<Store_Product> Store_Product { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vendor_Order_Detail> Vendor_Order_Detail { get; set; }
    }
}
