//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Feedback
    {
        public int ID_StoreFeedback { get; set; }
        public Nullable<int> ID_Store { get; set; }
        public string UserName { get; set; }
        public string StoreFeedback { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
