//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store_Product()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
            this.Product_Feedback = new HashSet<Product_Feedback>();
        }
    
        public int ID_StoreProduct { get; set; }
        public Nullable<int> ID_Store { get; set; }
        public Nullable<int> ID_Product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Feedback> Product_Feedback { get; set; }
        public virtual Store Store { get; set; }
    }
}
