//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Order_Detail
    {
        public int ID_Order { get; set; }
        public Nullable<int> ID_StoreProduct { get; set; }
        public Nullable<int> CashAmount { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> PickupTime { get; set; }
        public string Status { get; set; }
    }
}
